from enum import Enum


class WorkerAction(str, Enum):
    TURN_OFF_POWER = "TURN_OFF_POWER"
    OPEN_ISOLATION_VALVE = "OPEN_ISOLATION_VALVE"
    CLOSE_ISOLATION_VALVE = "CLOSE_ISOLATION_VALVE"
    DEPRESSURIZE = "DEPRESSURIZE"
    APPLY_LOCKOUT = "APPLY_LOCKOUT"
    VERIFY_ZERO_ENERGY = "VERIFY_ZERO_ENERGY"
    REMOVE_PRESSURE_CAP = "REMOVE_PRESSURE_CAP"
    REMOVE_FILTER = "REMOVE_FILTER"
    INSTALL_FILTER = "INSTALL_FILTER"
    INSTALL_PRESSURE_CAP = "INSTALL_PRESSURE_CAP"
    VERIFY_WORK_AREA_CLEAR = "VERIFY_WORK_AREA_CLEAR"
    REMOVE_LOCKOUT = "REMOVE_LOCKOUT"
    START_MACHINE = "START_MACHINE"


class SafetyStatus(str, Enum):
    SAFE = "SAFE"
    CAUTION = "CAUTION"
    BLOCKED = "BLOCKED"


class EmergencyLevel(str, Enum):
    NORMAL = "NORMAL"
    CAUTION = "CAUTION"
    CRITICAL = "CRITICAL"
